name: "sast-scan"

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Installation
      run: |
       curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh
       pwd
       find ~/ -type f -executable
       ~/bin/bearer scan -f html --output ./shop.html .

    - name: Report Upload
      uses: actions/upload-artifact@v2
      with:
        name: sast report
        path: |
          ./shop.html
