name: Dastardly Scan

on: [push]

permissions:
    contents: read
    checks: write

jobs:
  scan-with-dastardly:
    name: Scan with Dastardly
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      checks: write 
    
    steps:
      - name: Run Dastardly Scan
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'http://testphp.vulnweb.com/'

      - name: Publish Dastardly Scan Report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          application_id: ${{ secrets.APPLICATION_ID}}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY}}
          check_name: 'Dastardly Scan Report'
          report_paths: '**/dastardly-report.xml'
          require_tests: true
