name: Dastardly Scan

on: [push]

permissions:
  contents: read
  checks: write 

jobs:
  scan-with-dastardly:
    name: Scan with Dastardly
    runs-on: ubuntu-latest
       
    steps:
      - name: Run Dastardly Scan
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'http://testphp.vulnweb.com/'

      - name: Publish Dastardly Scan Report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          check_name: 'Dastardly Scan Report'
          report_paths: '**/dastardly-report.xml'
          require_tests: true
