name: OWASP ZAP Scan

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
       
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          #token: ${{ secrets.Personal_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://juice-shop.herokuapp.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
      
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with: 
          status: ${{ job.status }}
          channel: '#integration'
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
          
          
#       - name: Publish
#         uses: actions/upload-artifact@v3
#         with:
#          name: Owasp Report
#          path: report_html.html
