name: OWASP ZAP Scan

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    env:
       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
       
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          #token: ${{ secrets.Personal_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://juice-shop.herokuapp.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
      
      - name: Slack Notification
        uses: act10ns/slack@v1
        with: 
          #status: ${{ job.status }}
          channel: '#integration'
          message: Owasp ZAP Scan Completed
          
          
#       - name: Publish
#         uses: actions/upload-artifact@v3
#         with:
#          name: Owasp Report
#          path: report_html.html
