name: Semgrep-cli

on:
  push:
    branches:
    - master
    

jobs:
  semgrep:
    name: semgrep/ci
    
    runs-on: ubuntu-latest
    
    container:
      image: returntocorp/semgrep
      
    steps:
    - uses: actions/checkout@v3
    
    - name: full scan
      run: |
        semgrep --junit-xml --output report.xml --timeout-threshold 30 --max-target-bytes 3000000
      env:
        SEMGREP_RULES: p/default p/owasp-top-ten p/cwe-top-25
        #Explore the various rule set here https://semgrep.dev/explore
        
    - name: save report as pipeline artifact
      uses: actions/upload-artifact@v3
      with:
        name: junit-report
        path: report.xml
