name: Semgrep

on:
  push:
    branches:
    - master
    

jobs:
  semgrep:
    name: semgrep/ci
    
    runs-on: ubuntu-latest
    
    container:
      image: returntocorp/semgrep
      
    steps:
    - uses: actions/checkout@v3
    
    - name: full scan
      run: |
        semgrep --text --output report.txt --timeout-threshold 60 --max-target-bytes 3000000
      env:
        SEMGREP_RULES: p/default p/owasp-top-ten p/cwe-top-25
        #Explore the various rule set here https://semgrep.dev/explore
        
    - name: save report as pipeline artifact
      uses: actions/upload-artifact@v3
      with:
        name: report.txt
        path: report.txt
