name: Semgrep

on:
  push:
    branches:
    - master
    

jobs:
  semgrep:
    name: semgrep/ci
    
    runs-on: ubuntu-latest
    
    container:
      image: returntocorp/semgrep
      
    steps:
    - uses: actions/checkout@v3
    
    - name: full scan
      run: |
        semgrep --sarif --output report.sarif --config="p/default"
        
    - name: save report as pipeline artifact
      uses: actions/upload-artifact@v3
      with:
        name: report.sarif
        path: report.sarif
