name: Snyk Security

on:
  push:
    branches: ["master" ]
  pull_request:
    branches: ["master"]

jobs:
  snyk:
   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
